### ISSUE TITLE
latest release make error

### ISSUE THREAD

**Issue by sdxy36** [rafi/vim-config#111]
```
~/.config/nvim$ make
[vim-etc] 'Vim(return):E474: Unidentified byte: /usr/lib/ruby/2.5.0/psych.rb:402:in `parse'': (<unknown>): found unexpected '':'' while scanning a plain scalar at line 16 column 39 (Psych::SyntaxError)^@^Ifrom /usr/lib/ruby/2.5.0/psych.rb:402:in `parse_stream''^@^Ifrom /usr/lib/ruby/2.5.0/psych.rb:350:in `parse''^@^Ifrom /usr/lib/ruby/2.5.0/psych.rb:263:in `load''^@^Ifrom -e:1:in `<main>''^@'
[vim-etc] Error loading /home/messi/.config/nvim/config/plugins.yaml
[vim-etc] Caught: 'Vim(return):E474: Unidentified byte: /usr/lib/ruby/2.5.0/psych.rb:402:in `parse'': (<unknown>): found unexpected '':'' while scanning a plain scalar at line 16 column 39 (Psych::SyntaxError)^@^Ifrom /usr/lib/ruby/2.5.0/psych.rb:402:in `parse_stream''^@^Ifrom /usr/lib/ruby/2.5.0/psych.rb:350:in `parse''^@^Ifrom /usr/lib/ruby/2.5.0/psych.rb:263:in `load''^@^Ifrom -e:1:in `<main>''^@'
[vim-etc] Please run: pip install --user PyYAML
[vim-etc] Empty plugin list
Error loading colorscheme "hybrid"
Press ENTER or type command to continue

**Comment by rafi** [comment]
Fixed in latest commit. Thanks
