### ISSUE TITLE
Installation does not working properly and does not load local.plugins.vim

### ISSUE THREAD

**Issue by andrius** [rafi/vim-config#113]
I do have debian linux with homebrew and both python2 and 3, when executing `make install` with current master-branch version,I get following:

```rm -rf ~/.cache/vim/backup ~/.cache/vim/dein ~/.cache/vim/dein.log ~/.cache/vim/theme.txt ~/.cache/vim/venv
ls -lai ~/.cache/vim
# total 52
#  666079 drwxr-xr-x  7 ak ak  4096 Aug  5 09:37 .
#  393738 drwx------ 13 ak ak  4096 Aug  1 14:25 ..
# 1453251 drwxr-xr-x  2 ak ak  4096 Aug  5 09:17 session
#  666977 drwxr-xr-x  2 ak ak  4096 Aug  5 09:23 snippets
#  666111 drwxr-xr-x  2 ak ak  4096 Aug  5 09:35 swap
#  666121 drwxr-xr-x  2 ak ak  4096 Aug  5 09:35 tags
#  666132 drwxr-xr-x  2 ak ak 20480 Aug  5 09:35 undo
#  666973 -rw-r--r--  1 ak ak    99 Aug  5 09:35 bookmarks

make install

# there I get two errors:

[dein] ( 67/137) [+++++++++-----------] vim-cool
[dein] ( 68/137) [+++++++++-----------] unite-location
[dein] Error occurred while executing hook: fruzzy
[dein] Vim(call):E117: Unknown function: fruzzy#install[dein] ( 73/137) [++++++++++----------] vim-log-highlighting
[dein] ( 74/137) [++++++++++----------] vim-lua
[dein] ( 75/137) [++++++++++----------] vim-edgemotion

# and

[dein]   deoplete-jedi(1 change)
[dein] Error occurred while executing hook: neomake
[dein] Vim(if):E121: Undefined variable: g:python3_host_prog
[dein] Vim(autocmd):E216: No such group or event: CompleteChanged * call float_preview#_menu_popup_changed()
[dein] /home/ak/.cache/vim/dein/repos/github.com/ncm2/float-preview.nvim/plugin/float_preview.vim, line 14

# and message "the installation is not finished, cancel now? yes/no
```

After there messages, it does installing all the python3 things. Background info if needed:

```
~/.config/nvim master ak@ak 2m 27s
❯ which python
/home/linuxbrew/.linuxbrew/bin/python

~/.config/nvim master ak@ak
❯ which python3
/home/linuxbrew/.linuxbrew/bin/python3

~/.config/nvim master ak@ak
❯ which python2
/home/linuxbrew/.linuxbrew/bin/python2

~/.config/nvim master ak@ak
❯ ls -lai $(which python)
141591 lrwxrwxrwx 1 ak ak 36 Mar  7 10:19 /home/linuxbrew/.linuxbrew/bin/python -> ../Cellar/python@2/2.7.16/bin/python
```

**Comment by rafi** [comment]
Hi @andrius - thanks for the report. After running n/vim the 2nd time, does it work?
Can you disable fruzzy from plugins.yaml and try again?
I'll look into these problems.

**Comment by andrius** [comment]
I have tried to disable it, also manually installed virtualenv for python2 (did not needed with past versions etc). After few attempts, I just rollback to pervious version, this one b4bfc53 works

**Comment by andrius** [comment]
Update: just enclosed my local* files: https://gist.github.com/1912bb4d48997287ad9d5a6e16552938

**Comment by Sacro** [comment]
Seconded, local.plugins.vim isn't getting pulled in.

**Comment by rbelem** [comment]
I got the following errors after upgrading

`[vim-etc] 'Vim(return):E474: Unidentified byte: /usr/lib/ruby/2.6.0/psych.rb:456:in 'parse'': (<unknown>): found unexpected '':'' while scanning a plain scalar at line
16 column 39 (Psych::SyntaxError)^@^Ifrom /usr/lib/ruby/2.6.0/psych.rb:456:in 'parse_stream''^@^Ifrom /usr/lib/ruby/2.6.0/psych.rb:390:in 'parse''^@^Ifrom /usr/lib/ruby
/2.6.0/psych.rb:277:in 'load''^@^Ifrom -e:1:in '<main>''^@'
[vim-etc] Error loading /home/rodrigo/.config/nvim/config/plugins.yaml
[vim-etc] Caught: 'Vim(return):E474: Unidentified byte: /usr/lib/ruby/2.6.0/psych.rb:456:in 'parse'': (<unknown>): found unexpected '':'' while scanning a plain scalar
at line 16 column 39 (Psych::SyntaxError)^@^Ifrom /usr/lib/ruby/2.6.0/psych.rb:456:in 'parse_stream''^@^Ifrom /usr/lib/ruby/2.6.0/psych.rb:390:in 'parse''^@^Ifrom /usr/
lib/ruby/2.6.0/psych.rb:277:in 'load''^@^Ifrom -e:1:in '<main>''^@'

Error loading colorscheme "hybrid"
Press ENTER or type command to continue`

**Comment by rbelem** [comment]
dein.log contents:
`  You may have used the wrong plugin name, or all of the plugins are already installed.
  Target plugins are not found.                                                   
  You may have used the wrong plugin name, or all of the plugins are already installed.
  Runtimepath updated: (2019/08/05 21:42:27)`

**Comment by rbelem** [comment]
Clean install error:
```
:!git clone https://github.com/Shougo/dein.vim /home/rodrigo/.cache/vim/dein/repos/github.com/Shougo/dein.vim
Cloning into '/home/rodrigo/.cache/vim/dein/repos/github.com/Shougo/dein.vim'...

[vim-etc] 'Vim(return):E474: Unidentified byte: /usr/lib/ruby/2.6.0/psych.rb:456:in `parse'': (<unknown>): found unexpected '':'' while scanning a plain scalar at line
16 column 39 (Psych::SyntaxError)^@^Ifrom /usr/lib/ruby/2.6.0/psych.rb:456:in `parse_stream''^@^Ifrom /usr/lib/ruby/2.6.0/psych.rb:390:in `parse''^@^Ifrom /usr/lib/ruby
/2.6.0/psych.rb:277:in `load''^@^Ifrom -e:1:in `<main>''^@'
[vim-etc] Error loading /home/rodrigo/.config/nvim/config/plugins.yaml
[vim-etc] Caught: 'Vim(return):E474: Unidentified byte: /usr/lib/ruby/2.6.0/psych.rb:456:in `parse'': (<unknown>): found unexpected '':'' while scanning a plain scalar
at line 16 column 39 (Psych::SyntaxError)^@^Ifrom /usr/lib/ruby/2.6.0/psych.rb:456:in `parse_stream''^@^Ifrom /usr/lib/ruby/2.6.0/psych.rb:390:in `parse''^@^Ifrom /usr/
lib/ruby/2.6.0/psych.rb:277:in `load''^@^Ifrom -e:1:in `<main>''^@'

Error loading colorscheme "hybrid"
[dein] Target plugins are not found.
[dein] You may have used the wrong plugin name, or all of the plugins are already installed.

[O]k:
```

**Comment by rbelem** [comment]
Looks like the issue is in this line

```
diff --git a/config/plugins.yaml b/config/plugins.yaml
index 05194f0..c09ef7d 100644
--- a/config/plugins.yaml
+++ b/config/plugins.yaml
@@ -13,7 +13,7 @@
 - repo: thinca/vim-localrc
 - repo: romainl/vim-cool
 - repo: sgur/vim-editorconfig
-- { repo: tpope/vim-sleuth, hook_add: let g:sleuth_neighbor_limit = 5 }
+  #- { repo: tpope/vim-sleuth, hook_add: let g:sleuth_neighbor_limit = 5 }
 
 # GUI only:
 - { repo: equalsraf/neovim-gui-shim, if: has('gui_running') }
```

**Comment by rbelem** [comment]
The following change fixed the issue for me
```
diff --git a/config/plugins.yaml b/config/plugins.yaml
index 05194f0..56df104 100644
--- a/config/plugins.yaml
+++ b/config/plugins.yaml
@@ -13,7 +13,8 @@
 - repo: thinca/vim-localrc
 - repo: romainl/vim-cool
 - repo: sgur/vim-editorconfig
-- { repo: tpope/vim-sleuth, hook_add: let g:sleuth_neighbor_limit = 5 }
+- repo: tpope/vim-sleuth
+  hook_add: let g:sleuth_neighbor_limit = 5
 
 # GUI only:
 - { repo: equalsraf/neovim-gui-shim, if: has('gui_running') }
```

**Comment by Sacro** [comment]
Confirmed, that fixes it for me too!

**Comment by rafi** [comment]
Thanks for all the debug information. Seems I forgot to merge `config/local.plugins.yaml`, and ruby YAML had problems parsing. I also support [yq](https://github.com/mikefarah/yq) instead if you'd like. Hopefully everything is fixed.

**Comment by andrius** [comment]
Not, that's not all.

I've  removed all the cached data in ~/config, executed `./venv.sh` and then `make`, and get error:

```
[dein] Error occurred while executing hook: fruzzy
[dein] Vim(call):E117: Unknown function: fruzzy#install
```
and
```
[dein]   SimpylFold(1 change)
[dein]   deoplete-jedi(1 change)
[dein] Vim(autocmd):E216: No such group or event: CompleteChanged * call float_preview#_menu_popup_changed()
[dein] /home/ak/.cache/vim/dein/repos/github.com/ncm2/float-preview.nvim/plugin/float_preview.vim, line 14
Press ENTER or type command to continue


The installation has not finished. Cancel now?
(y)es, [N]o:
```

After installation, color highlighting works (so local plugins get installed, but `leader-b` wont trigger colorscheme and `second-leader b` thrown this:

```
                                             [denite] Vim(call):E117: Unknown function: _denite_init
[denite] function dein#autoload#_on_cmd[13]..denite#helper#call_denite[7]..denite#start[4]..<SNR>125_start[1]..denite#initialize[1]..denite#init#_initialize, line 33
[denite] denite failed to load. Try the :UpdateRemotePlugins command and restart Neovim. See also :checkhealth.
Press ENTER or type command to continue
```
Also have tried `make update` with following log
```[No Name]
[dein] function dein#update[1]..dein#install#_update[38]..<SNR>99_update_loop[5]..<SNR>99_install_async[13]..<SNR>99_print_progress_message[15]..<SNR>99_echo[18]..airline#extensions#neomake#get_error
s[1]..<SNR>77_get_counts, line 1


[O]k:
```
