### ISSUE TITLE
In macvim opening denite after defx causes defx import error.

### ISSUE THREAD

**Issue by chrischen** [rafi/vim-config#147]
Seems like opening defx file explorer causes denite to fail.
Steps to reproduce:

1. Run vim 8 in macvim (error does not occur in vim or nvim).
2. <space> l f e
3. ; f (find files)

```
[denite] Traceback (most recent call last):
[denite]   File "/Users/Chris/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 28, in start
[denite]     return ui.start(args[0], context)
[denite]   File "/Users/Chris/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 69, in start
[denite]     self._start_sources_queue(context)
[denite]   File "/Users/Chris/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 165, in _start_sources_queue
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/Users/Chris/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 212, in _start
[denite]     self._init_denite()
[denite]   File "/Users/Chris/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 859, in _init_denite
[denite]     self._denite.start(self._context)
[denite]   File "/Users/Chris/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/parent.py", line 44, in start
[denite]     self._put('start', [context])
[denite]   File "/Users/Chris/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/parent.py", line 80, in _put
[denite]     return self._child.main(name, args, queue_id=None)  # type: ignore
[denite]   File "/Users/Chris/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/child.py", line 67, in main
[denite]     self.start(args[0])
[denite]   File "/Users/Chris/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/child.py", line 93, in start
[denite]     self._load_sources(context)
[denite]   File "/Users/Chris/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/child.py", line 449, in _load_sources
[denite]     for SourceClass, path, _ in rplugins:
[denite]   File "/Users/Chris/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/util.py", line 256, in import_rplugins
[denite]     spec.loader.exec_module(module)  # type: ignore
[denite]   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
[denite]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[denite]   File "/Users/Chris/.cache/vim/dein/repos/github.com/Shougo/defx.nvim/rplugin/python3/denite/source/defx/session.py", line 7, in <module>
[denite]     from defx.util import Nvim, UserContext, Candidates
[denite] ModuleNotFoundError: No module named 'defx'
[denite] Please execute :messages command.   
```

**Comment by chrischen** [comment]
Can't seem to get it to reproduce anymore. May have been because I uninstalled neovim from python (already had pynvim).

**Comment by chrischen** [comment]
Removing python neovim did not solve. However issue doesn't happen consistently so it could be happening in neovim as wel.

**Comment by rafi** [comment]
@chrischen are you using **latest** pynvim python package, nvim and have updated `defx.nvim` plugin?
To update plugins, `:call dein#update()`

**Comment by mbellgb** [comment]
I'm running into this error on vim installed from homebrew (not macvim), so I'm wondering if this is a library issue and not a config issue. will do some exploring. for what it's worth, I just run a dein update and it seemed to resolve the issue for me. will update if that changes.

**Comment by rafi** [comment]
@mbellgb It sounds like https://github.com/roxma/nvim-yarp/issues/24

If you're using macOS, try this:
```sh
pip3 uninstall -y pynvim greenlet msgpack
brew reinstall python
pip3 install -U pynvim
```

**Comment by rafi** [comment]
I really recommend using Neovim though... ;)

**Comment by mbellgb** [comment]
> I really recommend using Neovim though... ;)

I'll have to give it a second look 🤘
