### ISSUE TITLE
The latest updated to Defx does not work with a fresh install

### ISSUE THREAD

**Issue by cj** [rafi/vim-config#155]
To reproduce do `git clone git://github.com/rafi/vim-config.git ~/.config/nvim` and then `make install` which will also update all plugins to the latest.  Open the nvim folder and pres `;e` you will get:

```
Error invoking '_defx_start' on channel 3 (python3-rplugin-host):^@error caught in request handler '_defx_start [[[], {'columns': 'indent:git:icons:filename', 'auto_cd': 0, 'winrelativ
e': 'editor', 'root_marker': '\uf149 ', 'resume': 1, 'close': 0, 'auto_recursive_level': 0, 'sort': 'filename', 'listed': 0, 'new': 0, 'ignored_files': '.mypy_cache,.pytest_cache,.git,
.hg,.svn,.stversions,__pycache__,.sass-cache,*.egg-info,.DS_Store,*.pyc', 'focus': 1, 'direction': 'topleft', 'visual_end': 0, 'winheight': 30, 'profile': 0, 'preview_height': 12, 'buf
fer_name': 'tab1', 'winwidth': 25, 'prev_bufnr': 1, 'split': 'vertical', 'preview_width': 40, 'visual_start': 0, 'cursor': 1, 'prev_last_bufnr': -1, 'search': '', 'prev_winid': 1000, '
wincol': 22, 'winrow': 9, 'session_file': '', 'floating_preview': 0, 'vertical_preview': 0, 'show_ignored_files': 0, 'drives': [], 'toggle': 1}]]':^@Traceback (most recent call last):^
@  File "/Users/cj/.cache/vim/dein/repos/github.com/Shougo/defx.nvim/rplugin/python3/defx/__init__.py", line 35, in start^@    self._rplugin.start(args)^@  File "/Users/cj/.cache/vim/d
ein/repos/github.com/Shougo/defx.nvim/rplugin/python3/defx/rplugin.py", line 26, in start^@    self.get_view(context).init_paths(^@  File "/Users/cj/.cache/vim/dein/repos/github.com/Sh
ougo/defx.nvim/rplugin/python3/defx/view.py", line 65, in init_paths^@    initialized = self._init_defx(clipboard)^@  File "/Users/cj/.cache/vim/dein/repos/github.com/Shougo/defx.nvim/
rplugin/python3/defx/view.py", line 480, in _init_defx^@    self._init_columns(self._context.columns.split(':'))^@  File "/Users/cj/.cache/vim/dein/repos/github.com/Shougo/defx.nvim/rp
lugin/python3/defx/view.py", line 584, in _init_columns^@    column.on_init(self, self._context)^@  File "/Users/cj/.cache/vim/dein/repos/github.com/kristijanhusak/defx-git/rplugin/pyt
hon3/defx/column/git.py", line 100, in on_init^@    self.vim.command(cmd)^@  File "/Users/cj/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 287, in command^@    return se
lf.request('nvim_command', string, **kwargs)^@  File "/Users/cj/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request^@    res = self._session.request(name, *arg
s, **kwargs)^@  File "/Users/cj/.local/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request^@    raise self.error_wrapper(err)^@pynvim.api.common.NvimError:
 Vim(syntax):E28: No such highlight group name: Defx_git_Untracked

```

**Comment by cj** [comment]
Looks like it's actually the latest updates to these which broke everything:

https://github.com/kristijanhusak/defx-icons
https://github.com/kristijanhusak/defx-git

**Comment by cj** [comment]
After reverting defx-icons and defx-git to older versions, there are also some changes to defx.nvim changed the color scheme.

**Comment by rafi** [comment]
Hi @cj. Yeah.. there are large changes in defx + its plugins. This should be reported upstream, I see there's already an issue at https://github.com/kristijanhusak/defx-git/issues/17

**Comment by cj** [comment]
@rafi looks like they fixed it.  The only issue is, the folder color is different.

**Comment by cj** [comment]
It is using PreProc for the text, so setting `hi PreProc ctermfg=110 guifg=#81a2be` fixes the folder text color.

**Comment by rafi** [comment]
Thanks for reporting @cj, appreciated!
