### ISSUE TITLE
deoplete-jedi update error

### ISSUE THREAD

**Issue by noamelf** [rafi/vim-config#27]
Error while running: `call dein#update()`
```
[dein] Update started: (2016/11/27 00:02:11)                                                                                                      
[dein] /home/noam/.cache/vim/dein/repos/github.com/zchee/deoplete-jedi                                                                            
[dein] Already up-to-date.error: no such remote ref 2ba78ab725f1e02dfef8bc50b0204cf656e8ee23                                                      
[dein] Fetched in submodule path 'rplugin/python3/deoplete/jedi', but it did not contain 2ba78ab725f1e02dfef8bc50b0204cf656e8ee23. Direct fetching
 of that commit failed.                                                                                                                           
[dein] Error installing plugins:                                                                                                                  
[dein]   deoplete-jedi                                              
```

Later when I use vim, and try to edit a file, I get:
```
 [deoplete] Traceback (most recent call last):                                                                                                     
[deoplete]   File "/home/noam/.cache/vim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 39, in completion_
begin                                                                                                                                             
[deoplete]     complete_position, candidates = self.gather_candidates(context)                                                                    
[deoplete]   File "/home/noam/.cache/vim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 58, in gather_cand
idates                                                                                                                                            
[deoplete]     self.check_recache(context)                                                                                                        
[deoplete]   File "/home/noam/.cache/vim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 368, in check_reca
che                                                                                                                                               
[deoplete]     self.on_event(context)                                                                                                             
[deoplete]   File "/home/noam/.cache/vim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 380, in on_event  
[deoplete]     source.on_event(context)                                                                                                           
[deoplete]   File "/home/noam/.cache/vim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/source/tag.py", line 34, in on_event 
[deoplete]     self.__tagfiles[context['bufnr']] = self.__get_tagfiles(context)                                                                   
[deoplete]   File "/home/noam/.cache/vim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/source/tag.py", line 58, in __get_tag
files                                                                                                                                             
[deoplete]     'exists', '*neoinclude#include#get_tag_files') else []                                                                             
[deoplete]   File "/usr/lib/python3.5/site-packages/neovim/api/nvim.py", line 230, in call                                                        
[deoplete]     return self.request('nvim_call_function', name, args, **kwargs)                                                                    
[deoplete]   File "/usr/lib/python3.5/site-packages/neovim/api/nvim.py", line 131, in request                                                     
[deoplete]     res = self._session.request(name, *args, **kwargs)                                                                                 
[deoplete]   File "/usr/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request                                           
[deoplete]     raise self.error_wrapper(err)                                                                                                      
[deoplete] neovim.api.nvim.NvimError: b'Vim(return):E121: Undefined variable: command'                                                            
[deoplete] Error while gathering completions.  Use :messages for error details.                                                                   
E45: 'readonly' option is set (add ! to override) 
```

**Comment by rafi** [comment]
deoplete-jedi contains vim-jedi as a git submodule. Seems something gone off there.
First, try to run from vim: `:call dein#reinstall(['deoplete-jedi'])`.
If that doesn't work,
```sh
cd ~/.cache/vim/dein/repos/github.com/zchee/deoplete-jedi
git submodule update --init --recursive
```

If everything fails, just delete the folder `~/.cache/vim/dein/repos/github.com/zchee/deoplete-jedi` and `:call dein#update()`

**Comment by noamelf** [comment]
I did the above, and I see no problem with the update process. Nevertheless, I still get deoplate related errors. This one shows when saving a file:
```
error caught in async handler 'deoplete_on_event [{'bufvars': {}, 'vars': {'deoplete#enable_smart_case': 1, 'deoplete#sources#jedi#statement_length': 0, 'deoplete#sources#go#sort_class': [], 'deoplete#delimiters': ['/', '.', '::', ':', '#'], 'deoplete#max_list': 100, 'deoplete#omni#input_patterns': {'javascript': '[^. \\t]\\.\\%\\(\\h\\w*\\)\\?', 'php': '\\w+|[^. \\t]->\\w*|\\w+::\\w*', 'python': ''}, 'deoplete#_omni_patterns': {'xml': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'markdown': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'html': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'xhtml': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'mkd': ['<', '<[^>]*\\s[[:alnum:]-]*']}, 'deoplete#sources#jedi#show_docstring': 1, 'deoplete#_rank': {}, 'deoplete#_neovim_python_version': ['0.1.11'], 'deoplete#ignore_sources': {}, 'deoplete#auto_complete_delay': 0, 'deoplete#sources#go#json_directory': '', 'deoplete#omni_patterns': {}, 'deoplete#_channel_id': 5, 'deoplete#enable_refresh_always': 0, 'deoplete#sources#go#gocode_binary': '', 'deoplete#enable_at_startup': 1, 'deoplete#max_menu_width': 40, 'deoplete#sources#go': 'vim-go', 'deoplete#sources#go#align_class': 0, 'deoplete#keyword_patterns': {'_': '[a-zA-Z_]\\k*\\(?'}, 'deoplete#tag#cache_limit_size': 5000000, 'deoplete#_context': {}, 'deoplete#sources#go#pointer': 0, 'deoplete#disable_auto_complete': 0, 'deoplete#omni#functions': {'php': 'phpcomplete_extended#CompletePHP', 'css': 'csscomplete#CompleteCSS'}, 'deoplete#member#prefix_patterns': {'javascript': ['\\.']}, 'deoplete#sources#go#use_cache': 0, 'deoplete#_keyword_patterns': {'_': '[a-zA-Z_]\\k*'}, 'deoplete#sources': {}, 'deoplete#auto_refresh_delay': 1000, 'deoplete#max_abbr_width': 80, 'deoplete#enable_profile': 0, 'deoplete#sources#go#on_event': 0, 'deoplete#enable_camel_case': 1, 'deoplete#enable_ignore_case': 1, 'deoplete#sources#jedi#short_types': 1, 'deoplete#auto_complete_start_length': 2, 'deoplete#sources#go#package_dot': 0, 'deoplete#sources#go#cgo': 0}, 'changedtick': 6, 'encoding': 'utf-8', 'start_complete': '\udc80\udcfdR_', 'complete_str': '', 'runtimepath': '/home/noam/.config/nvim,/etc/xdg/nvim,/home/noam/.local/share/nvim/site,/usr/local/share/nvim/site,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/parsec,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/wombat256,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/anderson,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/oceanicnext,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/rdark-terminal2,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/seoul256,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/apprentice,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/onedark,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/hybrid,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/flattened,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/lucius,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/gruvbox,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/focuspoint,/home/noam/.cache/vim/dein/repos/github.com/Shougo/vimproc.vim,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/pyte,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/lightning,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/flatcolor,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/molokayo,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/papercolor,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/molokai,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/hybrid-material,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/base16,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/twilight256,/home/noam/.cache/vim/d
in/repos/github.com/rafi/awesome-vim-colorschemes/atom,/home/noam/.cache/vim/dein/repos/github.com/rafi/awesome-vim-colorschemes/scheakur,/home/noam/.cache/vim/dein/repos/github.com/Shougo/neomru.vim,/home/noam/.cache/vim/dein/repos/github.com/Shougo/neoinclude.vim,/home/noam/.cache/vim/dein/repos/github.com/airblade/vim-gitgutter,/home/noam/.cache/vim/dein/repos/github.com/nathanaelkane/vim-indent-guides,/home/noam/.cache/vim/dein/repos/github.com/kshenoy/vim-signature,/home/noam/.cache/vim/dein/repos/github.com/PotatoesMaster/i3-vim-syntax,/home/noam/.cache/vim/dein/repos/github.com/Konfekt/FastFold,/home/noam/.cache/vim/dein/repos/github.com/osyo-manga/vim-anzu,/home/noam/.cache/vim/dein/repos/github.com/zchee/deoplete-jedi,/home/noam/.cache/vim/dein/repos/github.com/zchee/deoplete-go,/home/noam/.cache/vim/dein/repos/github.com/wellle/tmux-complete.vim,/home/noam/.cache/vim/dein/repos/github.com/Raimondi/delimitMate,/home/noam/.cache/vim/dein/repos/github.com/mattn/emmet-vim,/home/noam/.cache/vim/dein/repos/github.com/Shougo/deoplete.nvim,/home/noam/.cache/vim/dein/repos/github.com/Shougo/neco-syntax,/home/noam/.cache/vim/dein/repos/github.com/Shougo/context_filetype.vim,/home/noam/.cache/vim/dein/repos/github.com/lambdalisue/vim-findent,/home/noam/.cache/vim/dein/repos/github.com/m2mdas/phpcomplete-extended,/home/noam/.cache/vim/dein/.cache/init.vim/.dein,/usr/share/nvim/site,/usr/share/nvim/runtime,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/home/noam/.local/share/nvim/site/after,/etc/xdg/nvim/after,/home/noam/.config/nvim/after,/home/noam/.cache/vim/dein/repos/github.com/Shougo/dein.vim,/home/noam/.cache/vim/dein/.cache/init.vim/.dein/after,/home/noam/.cache/vim/dein/repos/github.com/kshenoy/vim-signature/after', 'bufnr': 1, 'position': [0, 211, 1, 0], 'next_input': '', 'filetype': 'i3', 'same_filetypes': [], 'sources': [], 'camelcase': 1, 'keyword_patterns': '[a-zA-Z_][a-zA-Z@0-9_Ã-Ã¿]*\\(?', 'ignorecase': 1, 'omni__omnifunc': '', 'bufname': '/home/noam/.config/i3/config', 'event': 'BufWritePost', 'dict__dictionary': '', 'filetypes': ['i3'], 'max_abbr_width': 114, 'max_menu_width': 114, 'delay': 0, 'cwd': '/home/noam/.config/nvim', 'smartcase': 1, 'custom': {'_': {'converters': ['converter_remove_paren', 'converter_remove_overlap', 'converter_truncate_abbr', 'converter_truncate_menu', 'converter_auto_delimiter']}}, 'input': '', 'rpc': 'deoplete_on_event'}]'
Traceback (most recent call last):

  File "/home/noam/.cache/vim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 62, in on_event
    self.__deoplete.on_event(context)

  File "/home/noam/.cache/vim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 380, in on_event
    source.on_event(context)

  File "/home/noam/.cache/vim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/source/tag.py", line 34, in on_event
    self.__tagfiles[context['bufnr']] = self.__get_tagfiles(context)

  File "/home/noam/.cache/vim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/source/tag.py", line 58, in __get_tagfiles
    'exists', '*neoinclude#include#get_tag_files') else []

  File "/usr/lib/python3.5/site-packages/neovim/api/nvim.py", line 230, in call
    return self.request('nvim_call_function', name, args, **kwargs)

  File "/usr/lib/python3.5/site-packages/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)

  File "/usr/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)

neovim.api.nvim.NvimError: b'Vim(return):E121: Undefined variable: command'

```

**Comment by rafi** [comment]
Very weird behavior. Can you post your `:CheckHealth` output?

**Comment by rafi** [comment]
@noamelf this seems to be a bug in `deoplete-jedi`, can you post the issue [there](https://github.com/zchee/deoplete-jedi/issues)?

**Comment by rafi** [comment]
@noamelf seems that the plugin `neoinclude` is crashing deoplete. Try my latest master revision. Also notice I normalized installation into `~/.config/nvim`

**Comment by noamelf** [comment]
Latest revision seems to fix the issue, thanks!!
