### ISSUE TITLE
problem with flake8

### ISSUE THREAD

**Issue by jerabaul29** [rafi/vim-config#85]
I use Ubuntu 18.04.

I installed following the readme. On a ```:w``` I get the error message:

```
Neomake: flake8: unexpected output. See :messages for more information.
```

The content of message is:

```
search hit BOTTOM, continuing at TOP
E486: Pattern not found: ERROR
"Main.py" 110L, 2626C [w]
[dein] Error occurred while executing hook: neomake
[dein] Vim(if):E121: Undefined variable: g:python3_host_prog
Neomake: flake8: unexpected output on stderr: Traceback (most recent call last):
  File "/home/j/.local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/j/.local/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/j/.local/lib/python2.7/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/home/j/.local/lib/python2.7/site-packages/flake8/main/application.py", line 383, in _run
    self.initialize(argv)
  File "/home/j/.local/lib/python2.7/site-packages/flake8/main/application.py", line 365, in initialize
    self.find_plugins()
  File "/home/j/.local/lib/python2.7/site-packages/flake8/main/application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "/home/j/.local/lib/python2.7/site-packages/flake8/plugins/manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/home/j/.local/lib/python2.7/site-packages/flake8/plugins/manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/j/.local/lib/python2.7/site-packages/flake8/plugins/manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "/home/j/.local/lib/python2.7/site-packages/flake8/plugins/manager.py", line 186, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to 'module' object has no attribute 'break_around_binary_operator'.
Neomake: flake8: unexpected output. See :messages for more information.
"Main.py" 110L, 2626C [w]
Neomake: flake8: unexpected output on stderr: Traceback (most recent call last):
  File "/home/j/.local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/j/.local/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/j/.local/lib/python2.7/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/home/j/.local/lib/python2.7/site-packages/flake8/main/application.py", line 383, in _run
    self.initialize(argv)
  File "/home/j/.local/lib/python2.7/site-packages/flake8/main/application.py", line 365, in initialize
    self.find_plugins()
  File "/home/j/.local/lib/python2.7/site-packages/flake8/main/application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "/home/j/.local/lib/python2.7/site-packages/flake8/plugins/manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/home/j/.local/lib/python2.7/site-packages/flake8/plugins/manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/j/.local/lib/python2.7/site-packages/flake8/plugins/manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "/home/j/.local/lib/python2.7/site-packages/flake8/plugins/manager.py", line 186, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to 'module' object has no attribute 'break_around_binary_operator'.  
Neomake: flake8: unexpected output. See :messages for more information.                                                                                                                
Press ENTER or type command to continue
```

Any idea how to fix this?

**Comment by sergiopatino** [comment]
This is a problem with flake8/pycodestyle version dependencies..

See: https://github.com/PyCQA/pycodestyle/issues/741

Basically you need to use pycodestyle<2.4.0

**Comment by rafi** [comment]
Did you get it right @jerabaul29 ?

**Comment by jerabaul29** [comment]
I just moved to spf13 for Python related stuff ;)
